# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 09:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselcover',
            name='cover',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='portfoliographic',
            name='graphic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=b''),
        ),
    ]
