# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170707_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliographic',
            name='site_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliographic',
            name='site_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
