# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_carouselcaption_caption_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselcaption',
            name='caption_number',
            field=models.IntegerField(),
        ),
    ]
