# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170708_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselcaption',
            name='caption_number',
        ),
    ]
