# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_carouselcaption_caption_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselcaption',
            name='caption_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
