# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170710_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselcover',
            name='alt',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
