# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_carouselcover_alt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioGraphic',
        ),
    ]
