# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 06:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_delete_portfoliographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('graphic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to=b'')),
                ('site_url', models.URLField(max_length=100)),
                ('graphic_no', models.IntegerField(unique=True)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
    ]
