# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_portfoliographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField(max_length=1000)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
