# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'Blog Entry', 'verbose_name_plural': 'Blog Entries'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
