# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 14:32
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170729_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_header',
            field=models.ImageField(default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to=b''),
            preserve_default=False,
        ),
    ]
