# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 13:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_blog_blog_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencewith',
            name='entry_dateicon',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_header',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfoliographic',
            name='graphic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to=''),
        ),
    ]
