# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170906_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_icon', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('skill_desc', models.CharField(max_length=150)),
                ('experienced', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comfort',
        ),
        migrations.DeleteModel(
            name='ExperienceWith',
        ),
    ]
