# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 10:05
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to='')),
                ('picture_url', models.URLField(blank=True, max_length=100)),
                ('picture_no', models.IntegerField(blank=True, unique=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
