# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20170912_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=3, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags1',
            field=models.TextField(default=4, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags2',
            field=models.TextField(default=5, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags3',
            field=models.TextField(default=7, max_length=25),
            preserve_default=False,
        ),
    ]
