# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20170916_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags3',
            field=models.CharField(max_length=25),
        ),
    ]
