# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20170912_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(to='web.Blog_tags'),
        ),
    ]
