# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 11:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20170916_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=1, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_tags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Blog'),
        ),
    ]
