# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20170916_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='b_tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='_blog_tags_+', to='web.Blog'),
        ),
    ]
