# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20170916_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags1',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags2',
            field=models.TextField(default=12, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags3',
            field=models.TextField(default=23, max_length=25),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=543, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
